"""
Adds a second batch of 80 words (40 N5 + 40 N4) to japanese_bot.db.
Kanji, readings, and English meanings were cross-checked against
jlptsensei.com's JLPT vocabulary lists; example sentences and Russian
translations were written to match, then checked against the current
DB to avoid duplicates with the 382 words already present.

Run on the VPS, in the bot's folder, with the venv active:

    source venv/bin/activate
    python3 add_words_batch2.py

Safe to run once. Running it twice will insert the words again as
duplicates (there's no UNIQUE constraint on `word`), so don't re-run
unless you first check what's already there.
"""
import sqlite3

DB_NAME = 'japanese_bot.db'

NEW_WORDS = [
    # --- N5 (40) ---
    {"word": "浴びる", "level": "N5", "romaji": "abiru", "en_meaning": "to bathe / to shower", "ru_meaning": "принимать душ",
     "example_jp": "朝、シャワーを浴びます。", "example_romaji": "Asa, shawaa o abimasu.",
     "example_en": "I take a shower in the morning.", "example_ru": "Утром я принимаю душ."},
    {"word": "危ない", "level": "N5", "romaji": "abunai", "en_meaning": "dangerous", "ru_meaning": "опасный",
     "example_jp": "この道は危ないです。", "example_romaji": "Kono michi wa abunai desu.",
     "example_en": "This road is dangerous.", "example_ru": "Эта дорога опасная."},
    {"word": "上げる", "level": "N5", "romaji": "ageru", "en_meaning": "to raise / to give", "ru_meaning": "поднимать; дарить",
     "example_jp": "手を上げてください。", "example_romaji": "Te o agete kudasai.",
     "example_en": "Please raise your hand.", "example_ru": "Пожалуйста, поднимите руку."},
    {"word": "赤", "level": "N5", "romaji": "aka", "en_meaning": "red", "ru_meaning": "красный (цвет)",
     "example_jp": "赤が好きです。", "example_romaji": "Aka ga suki desu.",
     "example_en": "I like red.", "example_ru": "Мне нравится красный."},
    {"word": "赤い", "level": "N5", "romaji": "akai", "en_meaning": "red", "ru_meaning": "красный",
     "example_jp": "あの車は赤いです。", "example_romaji": "Ano kuruma wa akai desu.",
     "example_en": "That car is red.", "example_ru": "Та машина красная."},
    {"word": "明るい", "level": "N5", "romaji": "akarui", "en_meaning": "bright", "ru_meaning": "светлый, яркий",
     "example_jp": "この部屋は明るいです。", "example_romaji": "Kono heya wa akarui desu.",
     "example_en": "This room is bright.", "example_ru": "Эта комната светлая."},
    {"word": "開ける", "level": "N5", "romaji": "akeru", "en_meaning": "to open (something)", "ru_meaning": "открывать",
     "example_jp": "窓を開けてください。", "example_romaji": "Mado o akete kudasai.",
     "example_en": "Please open the window.", "example_ru": "Пожалуйста, откройте окно."},
    {"word": "秋", "level": "N5", "romaji": "aki", "en_meaning": "autumn", "ru_meaning": "осень",
     "example_jp": "秋は涼しいです。", "example_romaji": "Aki wa suzushii desu.",
     "example_en": "Autumn is cool.", "example_ru": "Осенью прохладно."},
    {"word": "開く", "level": "N5", "romaji": "aku", "en_meaning": "to open (by itself)", "ru_meaning": "открываться",
     "example_jp": "ドアが開きました。", "example_romaji": "Doa ga akimashita.",
     "example_en": "The door opened.", "example_ru": "Дверь открылась."},
    {"word": "飴", "level": "N5", "romaji": "ame", "en_meaning": "candy", "ru_meaning": "конфета",
     "example_jp": "子供が飴を食べています。", "example_romaji": "Kodomo ga ame o tabete imasu.",
     "example_en": "The child is eating candy.", "example_ru": "Ребёнок ест конфету."},
    {"word": "あなた", "level": "N5", "romaji": "anata", "en_meaning": "you", "ru_meaning": "ты, вы",
     "example_jp": "あなたは学生ですか。", "example_romaji": "Anata wa gakusei desu ka.",
     "example_en": "Are you a student?", "example_ru": "Ты студент?"},
    {"word": "姉", "level": "N5", "romaji": "ane", "en_meaning": "older sister", "ru_meaning": "старшая сестра",
     "example_jp": "姉は医者です。", "example_romaji": "Ane wa isha desu.",
     "example_en": "My older sister is a doctor.", "example_ru": "Моя старшая сестра — врач."},
    {"word": "兄", "level": "N5", "romaji": "ani", "en_meaning": "older brother", "ru_meaning": "старший брат",
     "example_jp": "兄は大学生です。", "example_romaji": "Ani wa daigakusei desu.",
     "example_en": "My older brother is a university student.", "example_ru": "Мой старший брат — студент университета."},
    {"word": "青", "level": "N5", "romaji": "ao", "en_meaning": "blue", "ru_meaning": "синий (цвет)",
     "example_jp": "空は青です。", "example_romaji": "Sora wa ao desu.",
     "example_en": "The sky is blue.", "example_ru": "Небо синее."},
    {"word": "青い", "level": "N5", "romaji": "aoi", "en_meaning": "blue", "ru_meaning": "синий",
     "example_jp": "海は青いです。", "example_romaji": "Umi wa aoi desu.",
     "example_en": "The sea is blue.", "example_ru": "Море синее."},
    {"word": "アパート", "level": "N5", "romaji": "apaato", "en_meaning": "apartment", "ru_meaning": "квартира",
     "example_jp": "私はアパートに住んでいます。", "example_romaji": "Watashi wa apaato ni sunde imasu.",
     "example_en": "I live in an apartment.", "example_ru": "Я живу в квартире."},
    {"word": "洗う", "level": "N5", "romaji": "arau", "en_meaning": "to wash", "ru_meaning": "мыть",
     "example_jp": "食器を洗います。", "example_romaji": "Shokki o araimasu.",
     "example_en": "I wash the dishes.", "example_ru": "Я мою посуду."},
    {"word": "朝ご飯", "level": "N5", "romaji": "asagohan", "en_meaning": "breakfast", "ru_meaning": "завтрак",
     "example_jp": "朝ご飯を食べましたか。", "example_romaji": "Asagohan o tabemashita ka.",
     "example_en": "Did you eat breakfast?", "example_ru": "Ты завтракал?"},
    {"word": "明後日", "level": "N5", "romaji": "asatte", "en_meaning": "day after tomorrow", "ru_meaning": "послезавтра",
     "example_jp": "明後日、旅行に行きます。", "example_romaji": "Asatte, ryokou ni ikimasu.",
     "example_en": "I'm going on a trip the day after tomorrow.", "example_ru": "Послезавтра я еду в путешествие."},
    {"word": "遊ぶ", "level": "N5", "romaji": "asobu", "en_meaning": "to play", "ru_meaning": "играть",
     "example_jp": "公園で遊びましょう。", "example_romaji": "Kouen de asobimashou.",
     "example_en": "Let's play at the park.", "example_ru": "Давай поиграем в парке."},
    {"word": "暖かい", "level": "N5", "romaji": "atatakai", "en_meaning": "warm", "ru_meaning": "тёплый",
     "example_jp": "今日は暖かいです。", "example_romaji": "Kyou wa atatakai desu.",
     "example_en": "It's warm today.", "example_ru": "Сегодня тепло."},
    {"word": "後", "level": "N5", "romaji": "ato", "en_meaning": "after / behind", "ru_meaning": "после, позади",
     "example_jp": "後で電話します。", "example_romaji": "Ato de denwa shimasu.",
     "example_en": "I'll call you later.", "example_ru": "Я позвоню позже."},
    {"word": "厚い", "level": "N5", "romaji": "atsui", "en_meaning": "thick", "ru_meaning": "толстый",
     "example_jp": "この本は厚いです。", "example_romaji": "Kono hon wa atsui desu.",
     "example_en": "This book is thick.", "example_ru": "Эта книга толстая."},
    {"word": "晩ご飯", "level": "N5", "romaji": "bangohan", "en_meaning": "dinner", "ru_meaning": "ужин",
     "example_jp": "晩ご飯は何ですか。", "example_romaji": "Bangohan wa nan desu ka.",
     "example_en": "What's for dinner?", "example_ru": "Что на ужин?"},
    {"word": "番号", "level": "N5", "romaji": "bangou", "en_meaning": "number", "ru_meaning": "номер",
     "example_jp": "電話番号を教えてください。", "example_romaji": "Denwa bangou o oshiete kudasai.",
     "example_en": "Please tell me your phone number.", "example_ru": "Пожалуйста, скажите свой номер телефона."},
    {"word": "バス", "level": "N5", "romaji": "basu", "en_meaning": "bus", "ru_meaning": "автобус",
     "example_jp": "バスで学校に行きます。", "example_romaji": "Basu de gakkou ni ikimasu.",
     "example_en": "I go to school by bus.", "example_ru": "Я езжу в школу на автобусе."},
    {"word": "バター", "level": "N5", "romaji": "bataa", "en_meaning": "butter", "ru_meaning": "сливочное масло",
     "example_jp": "パンにバターを塗ります。", "example_romaji": "Pan ni bataa o nurimasu.",
     "example_en": "I spread butter on the bread.", "example_ru": "Я намазываю масло на хлеб."},
    {"word": "ベッド", "level": "N5", "romaji": "beddo", "en_meaning": "bed", "ru_meaning": "кровать",
     "example_jp": "ベッドで寝ます。", "example_romaji": "Beddo de nemasu.",
     "example_en": "I sleep in a bed.", "example_ru": "Я сплю на кровати."},
    {"word": "便利", "level": "N5", "romaji": "benri", "en_meaning": "convenient", "ru_meaning": "удобный",
     "example_jp": "このアプリは便利です。", "example_romaji": "Kono apuri wa benri desu.",
     "example_en": "This app is convenient.", "example_ru": "Это приложение удобное."},
    {"word": "ボールペン", "level": "N5", "romaji": "boorupen", "en_meaning": "ballpoint pen", "ru_meaning": "шариковая ручка",
     "example_jp": "ボールペンを貸してください。", "example_romaji": "Boorupen o kashite kudasai.",
     "example_en": "Please lend me a ballpoint pen.", "example_ru": "Пожалуйста, одолжи шариковую ручку."},
    {"word": "ボタン", "level": "N5", "romaji": "botan", "en_meaning": "button", "ru_meaning": "кнопка, пуговица",
     "example_jp": "このボタンを押してください。", "example_romaji": "Kono botan o oshite kudasai.",
     "example_en": "Please press this button.", "example_ru": "Пожалуйста, нажмите эту кнопку."},
    {"word": "帽子", "level": "N5", "romaji": "boushi", "en_meaning": "hat", "ru_meaning": "шляпа, кепка",
     "example_jp": "帽子をかぶっています。", "example_romaji": "Boushi o kabutte imasu.",
     "example_en": "I'm wearing a hat.", "example_ru": "Я в шляпе."},
    {"word": "文章", "level": "N5", "romaji": "bunshou", "en_meaning": "sentence", "ru_meaning": "предложение (текст)",
     "example_jp": "この文章は難しいです。", "example_romaji": "Kono bunshou wa muzukashii desu.",
     "example_en": "This sentence is difficult.", "example_ru": "Это предложение сложное."},
    {"word": "豚肉", "level": "N5", "romaji": "butaniku", "en_meaning": "pork", "ru_meaning": "свинина",
     "example_jp": "豚肉を買いました。", "example_romaji": "Butaniku o kaimashita.",
     "example_en": "I bought pork.", "example_ru": "Я купил свинину."},
    {"word": "茶色", "level": "N5", "romaji": "chairo", "en_meaning": "brown", "ru_meaning": "коричневый",
     "example_jp": "茶色のかばんが好きです。", "example_romaji": "Chairo no kaban ga suki desu.",
     "example_en": "I like the brown bag.", "example_ru": "Мне нравится коричневая сумка."},
    {"word": "茶碗", "level": "N5", "romaji": "chawan", "en_meaning": "rice bowl", "ru_meaning": "чашка для риса",
     "example_jp": "茶碗にご飯を入れます。", "example_romaji": "Chawan ni gohan o iremasu.",
     "example_en": "I put rice in the bowl.", "example_ru": "Я кладу рис в чашку."},
    {"word": "父", "level": "N5", "romaji": "chichi", "en_meaning": "father", "ru_meaning": "отец",
     "example_jp": "父は会社員です。", "example_romaji": "Chichi wa kaishain desu.",
     "example_en": "My father is a company employee.", "example_ru": "Мой отец — офисный работник."},
    {"word": "違う", "level": "N5", "romaji": "chigau", "en_meaning": "to differ / to be wrong", "ru_meaning": "отличаться, быть неверным",
     "example_jp": "それは違います。", "example_romaji": "Sore wa chigaimasu.",
     "example_en": "That's wrong.", "example_ru": "Это не так."},
    {"word": "小さな", "level": "N5", "romaji": "chiisana", "en_meaning": "small", "ru_meaning": "маленький",
     "example_jp": "小さな町に住んでいます。", "example_romaji": "Chiisana machi ni sunde imasu.",
     "example_en": "I live in a small town.", "example_ru": "Я живу в маленьком городке."},
    {"word": "近い", "level": "N5", "romaji": "chikai", "en_meaning": "near / close", "ru_meaning": "близкий",
     "example_jp": "駅から近いです。", "example_romaji": "Eki kara chikai desu.",
     "example_en": "It's close to the station.", "example_ru": "Это близко от станции."},

    # --- N4 (40) ---
    {"word": "上がる", "level": "N4", "romaji": "agaru", "en_meaning": "to rise", "ru_meaning": "подниматься",
     "example_jp": "物価が上がりました。", "example_romaji": "Bukka ga agarimashita.",
     "example_en": "Prices have risen.", "example_ru": "Цены поднялись."},
    {"word": "アルバイト", "level": "N4", "romaji": "arubaito", "en_meaning": "part-time job", "ru_meaning": "подработка",
     "example_jp": "カフェでアルバイトをしています。", "example_romaji": "Kafe de arubaito o shite imasu.",
     "example_en": "I have a part-time job at a cafe.", "example_ru": "Я работаю неполный день в кафе."},
    {"word": "遊び", "level": "N4", "romaji": "asobi", "en_meaning": "playing", "ru_meaning": "игра, развлечение",
     "example_jp": "子供の遊びは大切です。", "example_romaji": "Kodomo no asobi wa taisetsu desu.",
     "example_en": "Children's play is important.", "example_ru": "Игра для детей важна."},
    {"word": "集まる", "level": "N4", "romaji": "atsumaru", "en_meaning": "to gather (by itself)", "ru_meaning": "собираться",
     "example_jp": "皆が公園に集まりました。", "example_romaji": "Minna ga kouen ni atsumarimashita.",
     "example_en": "Everyone gathered at the park.", "example_ru": "Все собрались в парке."},
    {"word": "集める", "level": "N4", "romaji": "atsumeru", "en_meaning": "to collect (something)", "ru_meaning": "собирать, коллекционировать",
     "example_jp": "切手を集めています。", "example_romaji": "Kitte o atsumete imasu.",
     "example_en": "I'm collecting stamps.", "example_ru": "Я коллекционирую марки."},
    {"word": "倍", "level": "N4", "romaji": "bai", "en_meaning": "double", "ru_meaning": "вдвое, крат",
     "example_jp": "値段が二倍になりました。", "example_romaji": "Nedan ga nibai ni narimashita.",
     "example_en": "The price has doubled.", "example_ru": "Цена стала вдвое больше."},
    {"word": "場所", "level": "N4", "romaji": "basho", "en_meaning": "place", "ru_meaning": "место",
     "example_jp": "会議の場所を教えてください。", "example_romaji": "Kaigi no basho o oshiete kudasai.",
     "example_en": "Please tell me the location of the meeting.", "example_ru": "Пожалуйста, скажите место встречи."},
    {"word": "美術館", "level": "N4", "romaji": "bijutsukan", "en_meaning": "art museum", "ru_meaning": "художественный музей",
     "example_jp": "週末に美術館へ行きました。", "example_romaji": "Shuumatsu ni bijutsukan e ikimashita.",
     "example_en": "I went to the art museum on the weekend.", "example_ru": "На выходных я ходил в художественный музей."},
    {"word": "びっくり", "level": "N4", "romaji": "bikkuri", "en_meaning": "to be surprised", "ru_meaning": "удивление",
     "example_jp": "そのニュースにびっくりしました。", "example_romaji": "Sono nyuusu ni bikkuri shimashita.",
     "example_en": "I was surprised by that news.", "example_ru": "Я был удивлён этой новостью."},
    {"word": "ビル", "level": "N4", "romaji": "biru", "en_meaning": "building", "ru_meaning": "здание",
     "example_jp": "あの高いビルは銀行です。", "example_romaji": "Ano takai biru wa ginkou desu.",
     "example_en": "That tall building is a bank.", "example_ru": "То высокое здание — банк."},
    {"word": "僕", "level": "N4", "romaji": "boku", "en_meaning": "I (used by males)", "ru_meaning": "я (мужской вариант)",
     "example_jp": "僕は学生です。", "example_romaji": "Boku wa gakusei desu.",
     "example_en": "I am a student.", "example_ru": "Я студент."},
    {"word": "部長", "level": "N4", "romaji": "buchou", "en_meaning": "department manager", "ru_meaning": "начальник отдела",
     "example_jp": "部長に相談しました。", "example_romaji": "Buchou ni soudan shimashita.",
     "example_en": "I consulted with the department manager.", "example_ru": "Я посоветовался с начальником отдела."},
    {"word": "ぶどう", "level": "N4", "romaji": "budou", "en_meaning": "grapes", "ru_meaning": "виноград",
     "example_jp": "ぶどうはおいしいです。", "example_romaji": "Budou wa oishii desu.",
     "example_en": "Grapes are delicious.", "example_ru": "Виноград вкусный."},
    {"word": "文法", "level": "N4", "romaji": "bunpou", "en_meaning": "grammar", "ru_meaning": "грамматика",
     "example_jp": "日本語の文法は難しいです。", "example_romaji": "Nihongo no bunpou wa muzukashii desu.",
     "example_en": "Japanese grammar is difficult.", "example_ru": "Японская грамматика сложная."},
    {"word": "血", "level": "N4", "romaji": "chi", "en_meaning": "blood", "ru_meaning": "кровь",
     "example_jp": "血が出ています。", "example_romaji": "Chi ga dete imasu.",
     "example_en": "I'm bleeding.", "example_ru": "У меня кровь идёт."},
    {"word": "力", "level": "N4", "romaji": "chikara", "en_meaning": "strength / power", "ru_meaning": "сила",
     "example_jp": "彼は力が強いです。", "example_romaji": "Kare wa chikara ga tsuyoi desu.",
     "example_en": "He is strong.", "example_ru": "Он сильный."},
    {"word": "地理", "level": "N4", "romaji": "chiri", "en_meaning": "geography", "ru_meaning": "география",
     "example_jp": "地理の勉強が好きです。", "example_romaji": "Chiri no benkyou ga suki desu.",
     "example_en": "I like studying geography.", "example_ru": "Мне нравится изучать географию."},
    {"word": "中学校", "level": "N4", "romaji": "chuugakkou", "en_meaning": "junior high school", "ru_meaning": "средняя школа (неполная)",
     "example_jp": "中学校で英語を習いました。", "example_romaji": "Chuugakkou de eigo o naraimashita.",
     "example_en": "I learned English in junior high school.", "example_ru": "Я изучал английский в средней школе."},
    {"word": "注射", "level": "N4", "romaji": "chuusha", "en_meaning": "injection", "ru_meaning": "укол, инъекция",
     "example_jp": "病院で注射をしました。", "example_romaji": "Byouin de chuusha o shimashita.",
     "example_en": "I got an injection at the hospital.", "example_ru": "Мне сделали укол в больнице."},
    {"word": "駐車場", "level": "N4", "romaji": "chuushajou", "en_meaning": "parking lot", "ru_meaning": "автостоянка",
     "example_jp": "駐車場はどこですか。", "example_romaji": "Chuushajou wa doko desu ka.",
     "example_en": "Where is the parking lot?", "example_ru": "Где автостоянка?"},
    {"word": "大分", "level": "N4", "romaji": "daibu", "en_meaning": "considerably", "ru_meaning": "значительно",
     "example_jp": "大分よくなりました。", "example_romaji": "Daibu yoku narimashita.",
     "example_en": "It has gotten considerably better.", "example_ru": "Стало значительно лучше."},
    {"word": "大学生", "level": "N4", "romaji": "daigakusei", "en_meaning": "university student", "ru_meaning": "студент университета",
     "example_jp": "姉は大学生です。", "example_romaji": "Ane wa daigakusei desu.",
     "example_en": "My older sister is a university student.", "example_ru": "Моя старшая сестра — студентка университета."},
    {"word": "大事", "level": "N4", "romaji": "daiji", "en_meaning": "important", "ru_meaning": "важный",
     "example_jp": "家族が一番大事です。", "example_romaji": "Kazoku ga ichiban daiji desu.",
     "example_en": "Family is the most important.", "example_ru": "Семья — самое важное."},
    {"word": "大体", "level": "N4", "romaji": "daitai", "en_meaning": "roughly / mostly", "ru_meaning": "в основном, примерно",
     "example_jp": "大体分かりました。", "example_romaji": "Daitai wakarimashita.",
     "example_en": "I roughly understood.", "example_ru": "Я примерно понял."},
    {"word": "暖房", "level": "N4", "romaji": "danbou", "en_meaning": "heating", "ru_meaning": "отопление",
     "example_jp": "冬は暖房をつけます。", "example_romaji": "Fuyu wa danbou o tsukemasu.",
     "example_en": "I turn on the heating in winter.", "example_ru": "Зимой я включаю отопление."},
    {"word": "男性", "level": "N4", "romaji": "dansei", "en_meaning": "man / male", "ru_meaning": "мужчина",
     "example_jp": "あの男性は先生です。", "example_romaji": "Ano dansei wa sensei desu.",
     "example_en": "That man is a teacher.", "example_ru": "Тот мужчина — учитель."},
    {"word": "電報", "level": "N4", "romaji": "denpou", "en_meaning": "telegram", "ru_meaning": "телеграмма",
     "example_jp": "電報を送りました。", "example_romaji": "Denpou o okurimashita.",
     "example_en": "I sent a telegram.", "example_ru": "Я отправил телеграмму."},
    {"word": "電灯", "level": "N4", "romaji": "dentou", "en_meaning": "electric light", "ru_meaning": "электрическая лампа",
     "example_jp": "電灯をつけてください。", "example_romaji": "Dentou o tsukete kudasai.",
     "example_en": "Please turn on the light.", "example_ru": "Пожалуйста, включите свет."},
    {"word": "どんどん", "level": "N4", "romaji": "dondon", "en_meaning": "rapidly / more and more", "ru_meaning": "быстро, всё больше",
     "example_jp": "日本語がどんどん上手になります。", "example_romaji": "Nihongo ga dondon jouzu ni narimasu.",
     "example_en": "My Japanese is getting better and better.", "example_ru": "Мой японский становится всё лучше и лучше."},
    {"word": "泥棒", "level": "N4", "romaji": "dorobou", "en_meaning": "thief", "ru_meaning": "вор",
     "example_jp": "泥棒が入りました。", "example_romaji": "Dorobou ga hairimashita.",
     "example_en": "A thief broke in.", "example_ru": "Вор проник в дом."},
    {"word": "動物園", "level": "N4", "romaji": "doubutsuen", "en_meaning": "zoo", "ru_meaning": "зоопарк",
     "example_jp": "動物園でパンダを見ました。", "example_romaji": "Doubutsuen de panda o mimashita.",
     "example_en": "I saw a panda at the zoo.", "example_ru": "Я видел панду в зоопарке."},
    {"word": "枝", "level": "N4", "romaji": "eda", "en_meaning": "branch", "ru_meaning": "ветка",
     "example_jp": "木の枝が折れました。", "example_romaji": "Ki no eda ga oremashita.",
     "example_en": "The tree branch broke.", "example_ru": "Ветка дерева сломалась."},
    {"word": "エスカレーター", "level": "N4", "romaji": "esukareetaa", "en_meaning": "escalator", "ru_meaning": "эскалатор",
     "example_jp": "エスカレーターで上に行きます。", "example_romaji": "Esukareetaa de ue ni ikimasu.",
     "example_en": "I go up by escalator.", "example_ru": "Я поднимаюсь на эскалаторе."},
    {"word": "復習", "level": "N4", "romaji": "fukushuu", "en_meaning": "review (of learned material)", "ru_meaning": "повторение (учёбы)",
     "example_jp": "毎晩、復習をします。", "example_romaji": "Maiban, fukushuu o shimasu.",
     "example_en": "I review every night.", "example_ru": "Я повторяю материал каждый вечер."},
    {"word": "踏む", "level": "N4", "romaji": "fumu", "en_meaning": "to step on", "ru_meaning": "наступать (ногой)",
     "example_jp": "足を踏まれました。", "example_romaji": "Ashi o fumaremashita.",
     "example_en": "Someone stepped on my foot.", "example_ru": "Мне наступили на ногу."},
    {"word": "船", "level": "N4", "romaji": "fune", "en_meaning": "ship", "ru_meaning": "корабль",
     "example_jp": "船で島に行きました。", "example_romaji": "Fune de shima ni ikimashita.",
     "example_en": "I went to the island by ship.", "example_ru": "Я поплыл на остров на корабле."},
    {"word": "布団", "level": "N4", "romaji": "futon", "en_meaning": "futon (Japanese bedding)", "ru_meaning": "футон (постель)",
     "example_jp": "布団を敷きます。", "example_romaji": "Futon o shikimasu.",
     "example_en": "I lay out the futon.", "example_ru": "Я расстилаю футон."},
    {"word": "普通", "level": "N4", "romaji": "futsuu", "en_meaning": "usually / normal", "ru_meaning": "обычный, обычно",
     "example_jp": "普通は電車で行きます。", "example_romaji": "Futsuu wa densha de ikimasu.",
     "example_en": "I usually go by train.", "example_ru": "Обычно я езжу на поезде."},
    {"word": "ガラス", "level": "N4", "romaji": "garasu", "en_meaning": "glass (material)", "ru_meaning": "стекло",
     "example_jp": "ガラスが割れました。", "example_romaji": "Garasu ga waremashita.",
     "example_en": "The glass broke.", "example_ru": "Стекло разбилось."},
    {"word": "ガソリン", "level": "N4", "romaji": "gasorin", "en_meaning": "gasoline", "ru_meaning": "бензин",
     "example_jp": "ガソリンを入れます。", "example_romaji": "Gasorin o iremasu.",
     "example_en": "I put in gasoline.", "example_ru": "Я заправляюсь бензином."},
]


def main():
    conn = sqlite3.connect(DB_NAME)
    cur = conn.cursor()

    cur.execute("SELECT word FROM words")
    existing = {row[0] for row in cur.fetchall()}

    inserted = 0
    skipped = 0
    for w in NEW_WORDS:
        if w["word"] in existing:
            skipped += 1
            continue
        cur.execute(
            """INSERT INTO words
               (word, level, romaji, en_meaning, ru_meaning,
                example_jp, example_romaji, example_en, example_ru)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (w["word"], w["level"], w["romaji"], w["en_meaning"], w["ru_meaning"],
             w["example_jp"], w["example_romaji"], w["example_en"], w["example_ru"])
        )
        inserted += 1

    conn.commit()
    conn.close()
    print(f"✅ Inserted {inserted} new words, skipped {skipped} already present.")


if __name__ == "__main__":
    main()
