"""
Adds 150 words across N5, N4 and N3 to japanese_bot.db.

Kanji and readings come from the jlptsensei and japanesetest4you JLPT
vocabulary lists rather than from memory; example sentences and Russian
translations were written to match.

Run on the VPS, in the bot's folder, with the venv active:

    source venv/bin/activate
    python3 add_words_batch4.py
    python3 validate_words.py          # confirm nothing got mangled

Idempotent — words already anywhere in the table are skipped, so re-running
is safe. Note that the skip check spans ALL levels: a word already stored as
N4 won't be re-added as N3, which is why inserted counts can come out lower
than the list length.

Afterwards, refresh the audio cache and the git-tracked seed file:

    python3 prewarm_audio.py <your_telegram_id>
    python3 export_words.py && git add words_seed.json && git commit -m "More words"
"""
import sqlite3

DB_NAME = 'japanese_bot.db'

NEW_WORDS = [
    # ---------------- N5 ----------------
    {"word": "地下鉄", "level": "N5", "romaji": "chikatetsu", "en_meaning": "subway", "ru_meaning": "метро",
     "example_jp": "地下鉄で行きます。", "example_romaji": "Chikatetsu de ikimasu.",
     "example_en": "I'll go by subway.", "example_ru": "Я поеду на метро."},
    {"word": "大学", "level": "N5", "romaji": "daigaku", "en_meaning": "university", "ru_meaning": "университет",
     "example_jp": "大学で日本語を勉強します。", "example_romaji": "Daigaku de nihongo o benkyou shimasu.",
     "example_en": "I study Japanese at university.", "example_ru": "Я изучаю японский в университете."},
    {"word": "大丈夫", "level": "N5", "romaji": "daijoubu", "en_meaning": "all right / OK", "ru_meaning": "всё в порядке",
     "example_jp": "大丈夫ですか。", "example_romaji": "Daijoubu desu ka.",
     "example_en": "Are you all right?", "example_ru": "Вы в порядке?"},
    {"word": "大好き", "level": "N5", "romaji": "daisuki", "en_meaning": "to like very much", "ru_meaning": "очень нравится",
     "example_jp": "寿司が大好きです。", "example_romaji": "Sushi ga daisuki desu.",
     "example_en": "I love sushi.", "example_ru": "Я очень люблю суши."},
    {"word": "誰", "level": "N5", "romaji": "dare", "en_meaning": "who", "ru_meaning": "кто",
     "example_jp": "あの人は誰ですか。", "example_romaji": "Ano hito wa dare desu ka.",
     "example_en": "Who is that person?", "example_ru": "Кто тот человек?"},
    {"word": "出す", "level": "N5", "romaji": "dasu", "en_meaning": "to take out / to submit", "ru_meaning": "вынимать, подавать",
     "example_jp": "手紙を出しました。", "example_romaji": "Tegami o dashimashita.",
     "example_en": "I sent a letter.", "example_ru": "Я отправил письмо."},
    {"word": "出口", "level": "N5", "romaji": "deguchi", "en_meaning": "exit", "ru_meaning": "выход",
     "example_jp": "出口はあちらです。", "example_romaji": "Deguchi wa achira desu.",
     "example_en": "The exit is over there.", "example_ru": "Выход вон там."},
    {"word": "飛行機", "level": "N5", "romaji": "hikouki", "en_meaning": "airplane", "ru_meaning": "самолёт",
     "example_jp": "飛行機で日本へ行きます。", "example_romaji": "Hikouki de Nihon e ikimasu.",
     "example_en": "I'll fly to Japan.", "example_ru": "Я полечу в Японию на самолёте."},
    {"word": "暇", "level": "N5", "romaji": "hima", "en_meaning": "free time", "ru_meaning": "свободное время",
     "example_jp": "今日は暇です。", "example_romaji": "Kyou wa hima desu.",
     "example_en": "I'm free today.", "example_ru": "Сегодня я свободен."},
    {"word": "昼ご飯", "level": "N5", "romaji": "hirugohan", "en_meaning": "lunch", "ru_meaning": "обед",
     "example_jp": "昼ご飯を食べましょう。", "example_romaji": "Hirugohan o tabemashou.",
     "example_en": "Let's have lunch.", "example_ru": "Давайте пообедаем."},
    {"word": "一人", "level": "N5", "romaji": "hitori", "en_meaning": "one person / alone", "ru_meaning": "один человек",
     "example_jp": "一人で住んでいます。", "example_romaji": "Hitori de sunde imasu.",
     "example_en": "I live alone.", "example_ru": "Я живу один."},
    {"word": "本棚", "level": "N5", "romaji": "hondana", "en_meaning": "bookshelf", "ru_meaning": "книжная полка",
     "example_jp": "本棚に本を置きます。", "example_romaji": "Hondana ni hon o okimasu.",
     "example_en": "I put the book on the shelf.", "example_ru": "Я кладу книгу на полку."},
    {"word": "忙しい", "level": "N5", "romaji": "isogashii", "en_meaning": "busy", "ru_meaning": "занятой",
     "example_jp": "今週は忙しいです。", "example_romaji": "Konshuu wa isogashii desu.",
     "example_en": "I'm busy this week.", "example_ru": "На этой неделе я занят."},
    {"word": "痛い", "level": "N5", "romaji": "itai", "en_meaning": "painful / sore", "ru_meaning": "больной, болит",
     "example_jp": "頭が痛いです。", "example_romaji": "Atama ga itai desu.",
     "example_en": "My head hurts.", "example_ru": "У меня болит голова."},
    {"word": "上手", "level": "N5", "romaji": "jouzu", "en_meaning": "skillful / good at", "ru_meaning": "умелый, хорошо получается",
     "example_jp": "日本語が上手ですね。", "example_romaji": "Nihongo ga jouzu desu ne.",
     "example_en": "Your Japanese is good.", "example_ru": "Вы хорошо говорите по-японски."},
    {"word": "辛い", "level": "N5", "romaji": "karai", "en_meaning": "spicy", "ru_meaning": "острый",
     "example_jp": "このカレーは辛いです。", "example_romaji": "Kono karee wa karai desu.",
     "example_en": "This curry is spicy.", "example_ru": "Это карри острое."},
    {"word": "軽い", "level": "N5", "romaji": "karui", "en_meaning": "light (in weight)", "ru_meaning": "лёгкий",
     "example_jp": "このかばんは軽いです。", "example_romaji": "Kono kaban wa karui desu.",
     "example_en": "This bag is light.", "example_ru": "Эта сумка лёгкая."},
    {"word": "可愛い", "level": "N5", "romaji": "kawaii", "en_meaning": "cute", "ru_meaning": "милый",
     "example_jp": "この猫は可愛いです。", "example_romaji": "Kono neko wa kawaii desu.",
     "example_en": "This cat is cute.", "example_ru": "Этот кот милый."},
    {"word": "黄色い", "level": "N5", "romaji": "kiiroi", "en_meaning": "yellow", "ru_meaning": "жёлтый",
     "example_jp": "黄色い花が好きです。", "example_romaji": "Kiiroi hana ga suki desu.",
     "example_en": "I like yellow flowers.", "example_ru": "Мне нравятся жёлтые цветы."},
    {"word": "嫌い", "level": "N5", "romaji": "kirai", "en_meaning": "dislike / hate", "ru_meaning": "не нравится",
     "example_jp": "虫が嫌いです。", "example_romaji": "Mushi ga kirai desu.",
     "example_en": "I hate insects.", "example_ru": "Я не люблю насекомых."},
    {"word": "綺麗", "level": "N5", "romaji": "kirei", "en_meaning": "pretty / clean", "ru_meaning": "красивый, чистый",
     "example_jp": "部屋が綺麗になりました。", "example_romaji": "Heya ga kirei ni narimashita.",
     "example_en": "The room became clean.", "example_ru": "Комната стала чистой."},
    {"word": "汚い", "level": "N5", "romaji": "kitanai", "en_meaning": "dirty", "ru_meaning": "грязный",
     "example_jp": "手が汚いです。", "example_romaji": "Te ga kitanai desu.",
     "example_en": "My hands are dirty.", "example_ru": "У меня грязные руки."},
    {"word": "暗い", "level": "N5", "romaji": "kurai", "en_meaning": "dark", "ru_meaning": "тёмный",
     "example_jp": "外は暗いです。", "example_romaji": "Soto wa kurai desu.",
     "example_en": "It's dark outside.", "example_ru": "На улице темно."},
    {"word": "黒い", "level": "N5", "romaji": "kuroi", "en_meaning": "black", "ru_meaning": "чёрный",
     "example_jp": "黒い車が好きです。", "example_romaji": "Kuroi kuruma ga suki desu.",
     "example_en": "I like black cars.", "example_ru": "Мне нравятся чёрные машины."},
    {"word": "短い", "level": "N5", "romaji": "mijikai", "en_meaning": "short", "ru_meaning": "короткий",
     "example_jp": "この鉛筆は短いです。", "example_romaji": "Kono enpitsu wa mijikai desu.",
     "example_en": "This pencil is short.", "example_ru": "Этот карандаш короткий."},
    {"word": "難しい", "level": "N5", "romaji": "muzukashii", "en_meaning": "difficult", "ru_meaning": "трудный",
     "example_jp": "漢字は難しいです。", "example_romaji": "Kanji wa muzukashii desu.",
     "example_en": "Kanji is difficult.", "example_ru": "Иероглифы сложные."},
    {"word": "元気", "level": "N5", "romaji": "genki", "en_meaning": "healthy / energetic", "ru_meaning": "бодрый, здоровый",
     "example_jp": "お元気ですか。", "example_romaji": "O-genki desu ka.",
     "example_en": "How are you?", "example_ru": "Как вы себя чувствуете?"},
    {"word": "下手", "level": "N5", "romaji": "heta", "en_meaning": "unskillful / bad at", "ru_meaning": "неумелый, плохо получается",
     "example_jp": "料理が下手です。", "example_romaji": "Ryouri ga heta desu.",
     "example_en": "I'm bad at cooking.", "example_ru": "Я плохо готовлю."},
    {"word": "本当", "level": "N5", "romaji": "hontou", "en_meaning": "truth / really", "ru_meaning": "правда, действительно",
     "example_jp": "本当にありがとう。", "example_romaji": "Hontou ni arigatou.",
     "example_en": "Thank you very much.", "example_ru": "Большое спасибо."},
    {"word": "旅行", "level": "N5", "romaji": "ryokou", "en_meaning": "travel / trip", "ru_meaning": "путешествие",
     "example_jp": "来月旅行に行きます。", "example_romaji": "Raigetsu ryokou ni ikimasu.",
     "example_en": "I'm going on a trip next month.", "example_ru": "В следующем месяце я еду в путешествие."},
    {"word": "料理", "level": "N5", "romaji": "ryouri", "en_meaning": "cooking / cuisine", "ru_meaning": "блюдо, кулинария",
     "example_jp": "日本料理が好きです。", "example_romaji": "Nihon ryouri ga suki desu.",
     "example_en": "I like Japanese food.", "example_ru": "Мне нравится японская кухня."},
    {"word": "咲く", "level": "N5", "romaji": "saku", "en_meaning": "to bloom", "ru_meaning": "цвести",
     "example_jp": "桜が咲きました。", "example_romaji": "Sakura ga sakimashita.",
     "example_en": "The cherry blossoms bloomed.", "example_ru": "Сакура зацвела."},
    {"word": "散歩", "level": "N5", "romaji": "sanpo", "en_meaning": "a walk / stroll", "ru_meaning": "прогулка",
     "example_jp": "公園を散歩します。", "example_romaji": "Kouen o sanpo shimasu.",
     "example_en": "I take a walk in the park.", "example_ru": "Я гуляю в парке."},
    {"word": "洗濯", "level": "N5", "romaji": "sentaku", "en_meaning": "laundry / washing", "ru_meaning": "стирка",
     "example_jp": "今日は洗濯をします。", "example_romaji": "Kyou wa sentaku o shimasu.",
     "example_en": "I'll do laundry today.", "example_ru": "Сегодня я буду стирать."},
    {"word": "仕事", "level": "N5", "romaji": "shigoto", "en_meaning": "work / job", "ru_meaning": "работа",
     "example_jp": "仕事が終わりました。", "example_romaji": "Shigoto ga owarimashita.",
     "example_en": "Work is finished.", "example_ru": "Работа закончена."},
    {"word": "閉める", "level": "N5", "romaji": "shimeru", "en_meaning": "to close / to shut", "ru_meaning": "закрывать",
     "example_jp": "ドアを閉めてください。", "example_romaji": "Doa o shimete kudasai.",
     "example_en": "Please close the door.", "example_ru": "Пожалуйста, закройте дверь."},
    {"word": "知る", "level": "N5", "romaji": "shiru", "en_meaning": "to know", "ru_meaning": "знать",
     "example_jp": "その話を知っています。", "example_romaji": "Sono hanashi o shitte imasu.",
     "example_en": "I know that story.", "example_ru": "Я знаю эту историю."},
    {"word": "質問", "level": "N5", "romaji": "shitsumon", "en_meaning": "question", "ru_meaning": "вопрос",
     "example_jp": "質問があります。", "example_romaji": "Shitsumon ga arimasu.",
     "example_en": "I have a question.", "example_ru": "У меня есть вопрос."},
    {"word": "掃除", "level": "N5", "romaji": "souji", "en_meaning": "cleaning", "ru_meaning": "уборка",
     "example_jp": "部屋の掃除をします。", "example_romaji": "Heya no souji o shimasu.",
     "example_en": "I'll clean the room.", "example_ru": "Я уберу комнату."},
    {"word": "住む", "level": "N5", "romaji": "sumu", "en_meaning": "to live / to reside", "ru_meaning": "жить, проживать",
     "example_jp": "東京に住んでいます。", "example_romaji": "Toukyou ni sunde imasu.",
     "example_en": "I live in Tokyo.", "example_ru": "Я живу в Токио."},
    {"word": "座る", "level": "N5", "romaji": "suwaru", "en_meaning": "to sit", "ru_meaning": "садиться",
     "example_jp": "ここに座ってください。", "example_romaji": "Koko ni suwatte kudasai.",
     "example_en": "Please sit here.", "example_ru": "Пожалуйста, сядьте здесь."},
    {"word": "練習", "level": "N5", "romaji": "renshuu", "en_meaning": "practice", "ru_meaning": "практика, тренировка",
     "example_jp": "毎日練習します。", "example_romaji": "Mainichi renshuu shimasu.",
     "example_en": "I practise every day.", "example_ru": "Я тренируюсь каждый день."},
    {"word": "冷蔵庫", "level": "N5", "romaji": "reizouko", "en_meaning": "refrigerator", "ru_meaning": "холодильник",
     "example_jp": "冷蔵庫に牛乳があります。", "example_romaji": "Reizouko ni gyuunyuu ga arimasu.",
     "example_en": "There's milk in the fridge.", "example_ru": "В холодильнике есть молоко."},
    {"word": "来週", "level": "N5", "romaji": "raishuu", "en_meaning": "next week", "ru_meaning": "на следующей неделе",
     "example_jp": "来週会いましょう。", "example_romaji": "Raishuu aimashou.",
     "example_en": "Let's meet next week.", "example_ru": "Давайте встретимся на следующей неделе."},
    {"word": "来年", "level": "N5", "romaji": "rainen", "en_meaning": "next year", "ru_meaning": "в следующем году",
     "example_jp": "来年日本へ行きます。", "example_romaji": "Rainen Nihon e ikimasu.",
     "example_en": "I'm going to Japan next year.", "example_ru": "В следующем году я поеду в Японию."},
    {"word": "昼", "level": "N5", "romaji": "hiru", "en_meaning": "noon / daytime", "ru_meaning": "полдень, день",
     "example_jp": "昼に休みます。", "example_romaji": "Hiru ni yasumimasu.",
     "example_en": "I rest at noon.", "example_ru": "В полдень я отдыхаю."},

    # ---------------- N4 ----------------
    {"word": "経験", "level": "N4", "romaji": "keiken", "en_meaning": "experience", "ru_meaning": "опыт",
     "example_jp": "いい経験になりました。", "example_romaji": "Ii keiken ni narimashita.",
     "example_en": "It was a good experience.", "example_ru": "Это был хороший опыт."},
    {"word": "警察", "level": "N4", "romaji": "keisatsu", "en_meaning": "police", "ru_meaning": "полиция",
     "example_jp": "警察に電話しました。", "example_romaji": "Keisatsu ni denwa shimashita.",
     "example_en": "I called the police.", "example_ru": "Я позвонил в полицию."},
    {"word": "経済", "level": "N4", "romaji": "keizai", "en_meaning": "economy", "ru_meaning": "экономика",
     "example_jp": "経済のニュースを読みます。", "example_romaji": "Keizai no nyuusu o yomimasu.",
     "example_en": "I read economic news.", "example_ru": "Я читаю новости экономики."},
    {"word": "特急", "level": "N4", "romaji": "tokkyuu", "en_meaning": "limited express train", "ru_meaning": "экспресс",
     "example_jp": "特急で行きましょう。", "example_romaji": "Tokkyuu de ikimashou.",
     "example_en": "Let's take the express.", "example_ru": "Поедем на экспрессе."},
    {"word": "床屋", "level": "N4", "romaji": "tokoya", "en_meaning": "barber", "ru_meaning": "парикмахерская",
     "example_jp": "床屋で髪を切りました。", "example_romaji": "Tokoya de kami o kirimashita.",
     "example_en": "I got a haircut at the barber.", "example_ru": "Я подстригся в парикмахерской."},
    {"word": "無理", "level": "N4", "romaji": "muri", "en_meaning": "impossible / unreasonable", "ru_meaning": "невозможно",
     "example_jp": "それは無理です。", "example_romaji": "Sore wa muri desu.",
     "example_en": "That's impossible.", "example_ru": "Это невозможно."},
    {"word": "虫", "level": "N4", "romaji": "mushi", "en_meaning": "insect", "ru_meaning": "насекомое",
     "example_jp": "庭に虫がいます。", "example_romaji": "Niwa ni mushi ga imasu.",
     "example_en": "There are insects in the garden.", "example_ru": "В саду есть насекомые."},
    {"word": "息子", "level": "N4", "romaji": "musuko", "en_meaning": "son", "ru_meaning": "сын",
     "example_jp": "息子は五歳です。", "example_romaji": "Musuko wa gosai desu.",
     "example_en": "My son is five.", "example_ru": "Моему сыну пять лет."},
    {"word": "娘", "level": "N4", "romaji": "musume", "en_meaning": "daughter", "ru_meaning": "дочь",
     "example_jp": "娘は学校に行きます。", "example_romaji": "Musume wa gakkou ni ikimasu.",
     "example_en": "My daughter goes to school.", "example_ru": "Моя дочь ходит в школу."},
    {"word": "変", "level": "N4", "romaji": "hen", "en_meaning": "strange / weird", "ru_meaning": "странный",
     "example_jp": "変な音がしました。", "example_romaji": "Hen na oto ga shimashita.",
     "example_en": "There was a strange sound.", "example_ru": "Раздался странный звук."},
    {"word": "返事", "level": "N4", "romaji": "henji", "en_meaning": "reply / answer", "ru_meaning": "ответ",
     "example_jp": "返事をください。", "example_romaji": "Henji o kudasai.",
     "example_en": "Please reply.", "example_ru": "Пожалуйста, ответьте."},
    {"word": "拝見", "level": "N4", "romaji": "haiken", "en_meaning": "to look at (humble)", "ru_meaning": "смотреть (скромно)",
     "example_jp": "写真を拝見しました。", "example_romaji": "Shashin o haiken shimashita.",
     "example_en": "I looked at the photo.", "example_ru": "Я посмотрел фотографию."},
    {"word": "経つ", "level": "N4", "romaji": "tatsu", "en_meaning": "to pass (of time)", "ru_meaning": "проходить (о времени)",
     "example_jp": "三年が経ちました。", "example_romaji": "Sannen ga tachimashita.",
     "example_en": "Three years have passed.", "example_ru": "Прошло три года."},
    {"word": "怖い", "level": "N4", "romaji": "kowai", "en_meaning": "scary / frightening", "ru_meaning": "страшный",
     "example_jp": "その映画は怖いです。", "example_romaji": "Sono eiga wa kowai desu.",
     "example_en": "That movie is scary.", "example_ru": "Этот фильм страшный."},
    {"word": "遅い", "level": "N4", "romaji": "osoi", "en_meaning": "late / slow", "ru_meaning": "поздний, медленный",
     "example_jp": "もう遅いですね。", "example_romaji": "Mou osoi desu ne.",
     "example_en": "It's late already.", "example_ru": "Уже поздно."},
    {"word": "浅い", "level": "N4", "romaji": "asai", "en_meaning": "shallow", "ru_meaning": "мелкий",
     "example_jp": "この川は浅いです。", "example_romaji": "Kono kawa wa asai desu.",
     "example_en": "This river is shallow.", "example_ru": "Эта река мелкая."},
    {"word": "生きる", "level": "N4", "romaji": "ikiru", "en_meaning": "to live / to be alive", "ru_meaning": "жить, быть живым",
     "example_jp": "百歳まで生きたいです。", "example_romaji": "Hyakusai made ikitai desu.",
     "example_en": "I want to live to a hundred.", "example_ru": "Я хочу дожить до ста лет."},
    {"word": "動く", "level": "N4", "romaji": "ugoku", "en_meaning": "to move", "ru_meaning": "двигаться",
     "example_jp": "車が動きません。", "example_romaji": "Kuruma ga ugokimasen.",
     "example_en": "The car won't move.", "example_ru": "Машина не двигается."},
    {"word": "光る", "level": "N4", "romaji": "hikaru", "en_meaning": "to shine / to glitter", "ru_meaning": "светиться, блестеть",
     "example_jp": "星が光っています。", "example_romaji": "Hoshi ga hikatte imasu.",
     "example_en": "The stars are shining.", "example_ru": "Звёзды сияют."},
    {"word": "焼く", "level": "N4", "romaji": "yaku", "en_meaning": "to bake / to grill", "ru_meaning": "печь, жарить",
     "example_jp": "パンを焼きます。", "example_romaji": "Pan o yakimasu.",
     "example_en": "I bake bread.", "example_ru": "Я пеку хлеб."},
    {"word": "沸かす", "level": "N4", "romaji": "wakasu", "en_meaning": "to boil (water)", "ru_meaning": "кипятить",
     "example_jp": "お湯を沸かします。", "example_romaji": "Oyu o wakashimasu.",
     "example_en": "I'll boil some water.", "example_ru": "Я вскипячу воду."},
    {"word": "招待", "level": "N4", "romaji": "shoutai", "en_meaning": "invitation", "ru_meaning": "приглашение",
     "example_jp": "パーティーに招待されました。", "example_romaji": "Paatii ni shoutai saremashita.",
     "example_en": "I was invited to a party.", "example_ru": "Меня пригласили на вечеринку."},
    {"word": "説明書", "level": "N4", "romaji": "setsumeisho", "en_meaning": "instruction manual", "ru_meaning": "инструкция",
     "example_jp": "説明書を読んでください。", "example_romaji": "Setsumeisho o yonde kudasai.",
     "example_en": "Please read the manual.", "example_ru": "Прочитайте, пожалуйста, инструкцию."},
    {"word": "地震", "level": "N4", "romaji": "jishin", "en_meaning": "earthquake", "ru_meaning": "землетрясение",
     "example_jp": "昨日地震がありました。", "example_romaji": "Kinou jishin ga arimashita.",
     "example_en": "There was an earthquake yesterday.", "example_ru": "Вчера было землетрясение."},
    {"word": "台風", "level": "N4", "romaji": "taifuu", "en_meaning": "typhoon", "ru_meaning": "тайфун",
     "example_jp": "台風が来ています。", "example_romaji": "Taifuu ga kite imasu.",
     "example_en": "A typhoon is coming.", "example_ru": "Приближается тайфун."},
    {"word": "空港", "level": "N4", "romaji": "kuukou", "en_meaning": "airport", "ru_meaning": "аэропорт",
     "example_jp": "空港まで迎えに行きます。", "example_romaji": "Kuukou made mukae ni ikimasu.",
     "example_en": "I'll pick you up at the airport.", "example_ru": "Я встречу вас в аэропорту."},
    {"word": "港", "level": "N4", "romaji": "minato", "en_meaning": "harbour / port", "ru_meaning": "порт, гавань",
     "example_jp": "港に船があります。", "example_romaji": "Minato ni fune ga arimasu.",
     "example_en": "There's a ship in the harbour.", "example_ru": "В порту стоит корабль."},
    {"word": "工場", "level": "N4", "romaji": "koujou", "en_meaning": "factory", "ru_meaning": "завод, фабрика",
     "example_jp": "父は工場で働いています。", "example_romaji": "Chichi wa koujou de hataraite imasu.",
     "example_en": "My father works at a factory.", "example_ru": "Мой отец работает на заводе."},
    {"word": "会場", "level": "N4", "romaji": "kaijou", "en_meaning": "venue", "ru_meaning": "место проведения",
     "example_jp": "会場はどこですか。", "example_romaji": "Kaijou wa doko desu ka.",
     "example_en": "Where is the venue?", "example_ru": "Где место проведения?"},
    {"word": "受付", "level": "N4", "romaji": "uketsuke", "en_meaning": "reception desk", "ru_meaning": "стойка регистрации",
     "example_jp": "受付で聞いてください。", "example_romaji": "Uketsuke de kiite kudasai.",
     "example_en": "Please ask at reception.", "example_ru": "Спросите на ресепшене."},
    {"word": "予約", "level": "N4", "romaji": "yoyaku", "en_meaning": "reservation / booking", "ru_meaning": "бронь, запись",
     "example_jp": "レストランを予約しました。", "example_romaji": "Resutoran o yoyaku shimashita.",
     "example_en": "I booked a restaurant.", "example_ru": "Я забронировал ресторан."},
    {"word": "遠く", "level": "N4", "romaji": "tooku", "en_meaning": "far away", "ru_meaning": "далеко",
     "example_jp": "遠くに山が見えます。", "example_romaji": "Tooku ni yama ga miemasu.",
     "example_en": "You can see mountains in the distance.", "example_ru": "Вдали видны горы."},
    {"word": "以外", "level": "N4", "romaji": "igai", "en_meaning": "except / other than", "ru_meaning": "кроме",
     "example_jp": "日曜日以外は働きます。", "example_romaji": "Nichiyoubi igai wa hatarakimasu.",
     "example_en": "I work except on Sundays.", "example_ru": "Я работаю кроме воскресенья."},
    {"word": "生徒", "level": "N4", "romaji": "seito", "en_meaning": "pupil / student", "ru_meaning": "ученик",
     "example_jp": "生徒が三十人います。", "example_romaji": "Seito ga sanjuunin imasu.",
     "example_en": "There are thirty pupils.", "example_ru": "Тридцать учеников."},
    {"word": "校長", "level": "N4", "romaji": "kouchou", "en_meaning": "school principal", "ru_meaning": "директор школы",
     "example_jp": "校長先生が話します。", "example_romaji": "Kouchou sensei ga hanashimasu.",
     "example_en": "The principal will speak.", "example_ru": "Выступит директор школы."},
    {"word": "字", "level": "N4", "romaji": "ji", "en_meaning": "character / letter", "ru_meaning": "знак, буква",
     "example_jp": "字がきれいですね。", "example_romaji": "Ji ga kirei desu ne.",
     "example_en": "Your handwriting is neat.", "example_ru": "У вас красивый почерк."},
    {"word": "小説", "level": "N4", "romaji": "shousetsu", "en_meaning": "novel", "ru_meaning": "роман",
     "example_jp": "小説を読んでいます。", "example_romaji": "Shousetsu o yonde imasu.",
     "example_en": "I'm reading a novel.", "example_ru": "Я читаю роман."},
    {"word": "祖父", "level": "N4", "romaji": "sofu", "en_meaning": "grandfather", "ru_meaning": "дедушка",
     "example_jp": "祖父は八十歳です。", "example_romaji": "Sofu wa hachijussai desu.",
     "example_en": "My grandfather is eighty.", "example_ru": "Моему дедушке восемьдесят."},
    {"word": "祖母", "level": "N4", "romaji": "sobo", "en_meaning": "grandmother", "ru_meaning": "бабушка",
     "example_jp": "祖母は元気です。", "example_romaji": "Sobo wa genki desu.",
     "example_en": "My grandmother is well.", "example_ru": "Моя бабушка здорова."},
    {"word": "親", "level": "N4", "romaji": "oya", "en_meaning": "parent", "ru_meaning": "родитель",
     "example_jp": "親に相談します。", "example_romaji": "Oya ni soudan shimasu.",
     "example_en": "I'll consult my parents.", "example_ru": "Я посоветуюсь с родителями."},

    # ---------------- N3 ----------------
    {"word": "影", "level": "N3", "romaji": "kage", "en_meaning": "shadow", "ru_meaning": "тень",
     "example_jp": "木の影で休みます。", "example_romaji": "Ki no kage de yasumimasu.",
     "example_en": "I rest in the shade of a tree.", "example_ru": "Я отдыхаю в тени дерева."},
    {"word": "煙", "level": "N3", "romaji": "kemuri", "en_meaning": "smoke", "ru_meaning": "дым",
     "example_jp": "煙が見えます。", "example_romaji": "Kemuri ga miemasu.",
     "example_en": "I can see smoke.", "example_ru": "Виден дым."},
    {"word": "骨", "level": "N3", "romaji": "hone", "en_meaning": "bone", "ru_meaning": "кость",
     "example_jp": "骨を折りました。", "example_romaji": "Hone o orimashita.",
     "example_en": "I broke a bone.", "example_ru": "Я сломал кость."},
    {"word": "肌", "level": "N3", "romaji": "hada", "en_meaning": "skin", "ru_meaning": "кожа",
     "example_jp": "肌が乾いています。", "example_romaji": "Hada ga kawaite imasu.",
     "example_en": "My skin is dry.", "example_ru": "У меня сухая кожа."},
    {"word": "涙", "level": "N3", "romaji": "namida", "en_meaning": "tears", "ru_meaning": "слёзы",
     "example_jp": "涙が出ました。", "example_romaji": "Namida ga demashita.",
     "example_en": "Tears came out.", "example_ru": "У меня выступили слёзы."},
    {"word": "波", "level": "N3", "romaji": "nami", "en_meaning": "wave", "ru_meaning": "волна",
     "example_jp": "今日は波が高いです。", "example_romaji": "Kyou wa nami ga takai desu.",
     "example_en": "The waves are high today.", "example_ru": "Сегодня высокие волны."},
    {"word": "岩", "level": "N3", "romaji": "iwa", "en_meaning": "rock", "ru_meaning": "скала, камень",
     "example_jp": "大きい岩があります。", "example_romaji": "Ookii iwa ga arimasu.",
     "example_en": "There's a big rock.", "example_ru": "Там большая скала."},
    {"word": "泉", "level": "N3", "romaji": "izumi", "en_meaning": "spring / fountain", "ru_meaning": "источник, родник",
     "example_jp": "山に泉があります。", "example_romaji": "Yama ni izumi ga arimasu.",
     "example_en": "There's a spring in the mountain.", "example_ru": "В горах есть родник."},
    {"word": "宝", "level": "N3", "romaji": "takara", "en_meaning": "treasure", "ru_meaning": "сокровище",
     "example_jp": "家族は宝です。", "example_romaji": "Kazoku wa takara desu.",
     "example_en": "Family is a treasure.", "example_ru": "Семья — это сокровище."},
    {"word": "命", "level": "N3", "romaji": "inochi", "en_meaning": "life", "ru_meaning": "жизнь",
     "example_jp": "命は大切です。", "example_romaji": "Inochi wa taisetsu desu.",
     "example_en": "Life is precious.", "example_ru": "Жизнь драгоценна."},
    {"word": "息", "level": "N3", "romaji": "iki", "en_meaning": "breath", "ru_meaning": "дыхание",
     "example_jp": "深く息をしてください。", "example_romaji": "Fukaku iki o shite kudasai.",
     "example_en": "Please breathe deeply.", "example_ru": "Пожалуйста, дышите глубоко."},
    {"word": "夢中", "level": "N3", "romaji": "muchuu", "en_meaning": "absorbed in / crazy about", "ru_meaning": "увлечённый",
     "example_jp": "ゲームに夢中です。", "example_romaji": "Geemu ni muchuu desu.",
     "example_en": "I'm absorbed in the game.", "example_ru": "Я увлечён игрой."},
    {"word": "無駄", "level": "N3", "romaji": "muda", "en_meaning": "waste / futility", "ru_meaning": "напрасно, впустую",
     "example_jp": "時間の無駄です。", "example_romaji": "Jikan no muda desu.",
     "example_en": "It's a waste of time.", "example_ru": "Это пустая трата времени."},
    {"word": "自信", "level": "N3", "romaji": "jishin", "en_meaning": "self-confidence", "ru_meaning": "уверенность в себе",
     "example_jp": "自信を持ってください。", "example_romaji": "Jishin o motte kudasai.",
     "example_en": "Please have confidence.", "example_ru": "Будьте увереннее в себе."},
    {"word": "苦労", "level": "N3", "romaji": "kurou", "en_meaning": "hardship / trouble", "ru_meaning": "трудности, хлопоты",
     "example_jp": "苦労して覚えました。", "example_romaji": "Kurou shite oboemashita.",
     "example_en": "I learned it with difficulty.", "example_ru": "Я выучил это с трудом."},
    {"word": "文化", "level": "N3", "romaji": "bunka", "en_meaning": "culture", "ru_meaning": "культура",
     "example_jp": "日本の文化に興味があります。", "example_romaji": "Nihon no bunka ni kyoumi ga arimasu.",
     "example_en": "I'm interested in Japanese culture.", "example_ru": "Я интересуюсь японской культурой."},
    {"word": "社会", "level": "N3", "romaji": "shakai", "en_meaning": "society", "ru_meaning": "общество",
     "example_jp": "社会の問題を考えます。", "example_romaji": "Shakai no mondai o kangaemasu.",
     "example_en": "I think about social problems.", "example_ru": "Я думаю об общественных проблемах."},
    {"word": "政治", "level": "N3", "romaji": "seiji", "en_meaning": "politics", "ru_meaning": "политика",
     "example_jp": "政治の話は難しいです。", "example_romaji": "Seiji no hanashi wa muzukashii desu.",
     "example_en": "Talking about politics is difficult.", "example_ru": "Говорить о политике сложно."},
    {"word": "経済的", "level": "N3", "romaji": "keizaiteki", "en_meaning": "economical", "ru_meaning": "экономичный",
     "example_jp": "経済的な方法を選びます。", "example_romaji": "Keizaiteki na houhou o erabimasu.",
     "example_en": "I'll choose the economical method.", "example_ru": "Я выберу экономичный способ."},
    {"word": "技術", "level": "N3", "romaji": "gijutsu", "en_meaning": "technology / skill", "ru_meaning": "технология, техника",
     "example_jp": "新しい技術を学びます。", "example_romaji": "Atarashii gijutsu o manabimasu.",
     "example_en": "I learn new technology.", "example_ru": "Я изучаю новые технологии."},
    {"word": "研究", "level": "N3", "romaji": "kenkyuu", "en_meaning": "research", "ru_meaning": "исследование",
     "example_jp": "大学で研究しています。", "example_romaji": "Daigaku de kenkyuu shite imasu.",
     "example_en": "I do research at university.", "example_ru": "Я занимаюсь исследованиями в университете."},
    {"word": "調べる", "level": "N3", "romaji": "shiraberu", "en_meaning": "to investigate / to look up", "ru_meaning": "проверять, искать",
     "example_jp": "辞書で調べます。", "example_romaji": "Jisho de shirabemasu.",
     "example_en": "I'll look it up in a dictionary.", "example_ru": "Я посмотрю в словаре."},
    {"word": "比べる", "level": "N3", "romaji": "kuraberu", "en_meaning": "to compare", "ru_meaning": "сравнивать",
     "example_jp": "値段を比べましょう。", "example_romaji": "Nedan o kurabemashou.",
     "example_en": "Let's compare prices.", "example_ru": "Давайте сравним цены."},
    {"word": "含める", "level": "N3", "romaji": "fukumeru", "en_meaning": "to include", "ru_meaning": "включать",
     "example_jp": "税金を含めた値段です。", "example_romaji": "Zeikin o fukumeta nedan desu.",
     "example_en": "The price includes tax.", "example_ru": "Цена с учётом налога."},
    {"word": "続ける", "level": "N3", "romaji": "tsuzukeru", "en_meaning": "to continue", "ru_meaning": "продолжать",
     "example_jp": "勉強を続けます。", "example_romaji": "Benkyou o tsuzukemasu.",
     "example_en": "I'll continue studying.", "example_ru": "Я продолжу учиться."},
    {"word": "進む", "level": "N3", "romaji": "susumu", "en_meaning": "to advance / to proceed", "ru_meaning": "продвигаться",
     "example_jp": "仕事が進んでいます。", "example_romaji": "Shigoto ga susunde imasu.",
     "example_en": "The work is progressing.", "example_ru": "Работа продвигается."},
    {"word": "戻る", "level": "N3", "romaji": "modoru", "en_meaning": "to return / to go back", "ru_meaning": "возвращаться",
     "example_jp": "五時に戻ります。", "example_romaji": "Goji ni modorimasu.",
     "example_en": "I'll be back at five.", "example_ru": "Я вернусь в пять."},
    {"word": "覚える", "level": "N3", "romaji": "oboeru", "en_meaning": "to memorize / to remember", "ru_meaning": "запоминать",
     "example_jp": "漢字を覚えます。", "example_romaji": "Kanji o oboemasu.",
     "example_en": "I memorize kanji.", "example_ru": "Я запоминаю иероглифы."},
    {"word": "忘れる", "level": "N3", "romaji": "wasureru", "en_meaning": "to forget", "ru_meaning": "забывать",
     "example_jp": "かばんを忘れました。", "example_romaji": "Kaban o wasuremashita.",
     "example_en": "I forgot my bag.", "example_ru": "Я забыл сумку."},
    {"word": "伝える", "level": "N3", "romaji": "tsutaeru", "en_meaning": "to convey / to tell", "ru_meaning": "передавать, сообщать",
     "example_jp": "彼に伝えてください。", "example_romaji": "Kare ni tsutaete kudasai.",
     "example_en": "Please tell him.", "example_ru": "Пожалуйста, передайте ему."},
    {"word": "感謝", "level": "N3", "romaji": "kansha", "en_meaning": "gratitude", "ru_meaning": "благодарность",
     "example_jp": "感謝しています。", "example_romaji": "Kansha shite imasu.",
     "example_en": "I'm grateful.", "example_ru": "Я благодарен."},
    {"word": "尊敬", "level": "N3", "romaji": "sonkei", "en_meaning": "respect", "ru_meaning": "уважение",
     "example_jp": "先生を尊敬しています。", "example_romaji": "Sensei o sonkei shite imasu.",
     "example_en": "I respect my teacher.", "example_ru": "Я уважаю учителя."},
    {"word": "信じる", "level": "N3", "romaji": "shinjiru", "en_meaning": "to believe / to trust", "ru_meaning": "верить",
     "example_jp": "彼を信じています。", "example_romaji": "Kare o shinjite imasu.",
     "example_en": "I trust him.", "example_ru": "Я ему верю."},
    {"word": "期待", "level": "N3", "romaji": "kitai", "en_meaning": "expectation / hope", "ru_meaning": "ожидание, надежда",
     "example_jp": "結果を期待しています。", "example_romaji": "Kekka o kitai shite imasu.",
     "example_en": "I'm looking forward to the result.", "example_ru": "Я жду результата."},
    {"word": "遠慮", "level": "N3", "romaji": "enryo", "en_meaning": "restraint / holding back", "ru_meaning": "сдержанность, стеснение",
     "example_jp": "遠慮しないでください。", "example_romaji": "Enryo shinaide kudasai.",
     "example_en": "Please don't hold back.", "example_ru": "Пожалуйста, не стесняйтесь."},
    {"word": "迷惑", "level": "N3", "romaji": "meiwaku", "en_meaning": "trouble / nuisance", "ru_meaning": "беспокойство, неудобство",
     "example_jp": "迷惑をかけてすみません。", "example_romaji": "Meiwaku o kakete sumimasen.",
     "example_en": "Sorry for the trouble.", "example_ru": "Извините за беспокойство."},
    {"word": "許す", "level": "N3", "romaji": "yurusu", "en_meaning": "to forgive / to permit", "ru_meaning": "прощать, разрешать",
     "example_jp": "彼を許しました。", "example_romaji": "Kare o yurushimashita.",
     "example_en": "I forgave him.", "example_ru": "Я его простил."},
    {"word": "守る", "level": "N3", "romaji": "mamoru", "en_meaning": "to protect / to keep", "ru_meaning": "защищать, соблюдать",
     "example_jp": "約束を守ります。", "example_romaji": "Yakusoku o mamorimasu.",
     "example_en": "I'll keep my promise.", "example_ru": "Я сдержу обещание."},
    {"word": "救う", "level": "N3", "romaji": "sukuu", "en_meaning": "to rescue / to save", "ru_meaning": "спасать",
     "example_jp": "命を救いました。", "example_romaji": "Inochi o sukuimashita.",
     "example_en": "He saved a life.", "example_ru": "Он спас жизнь."},
    {"word": "働き", "level": "N3", "romaji": "hataraki", "en_meaning": "work / function", "ru_meaning": "работа, функция",
     "example_jp": "心臓の働きを調べます。", "example_romaji": "Shinzou no hataraki o shirabemasu.",
     "example_en": "We check how the heart functions.", "example_ru": "Мы проверяем работу сердца."},
    {"word": "収入", "level": "N3", "romaji": "shuunyuu", "en_meaning": "income", "ru_meaning": "доход",
     "example_jp": "収入が増えました。", "example_romaji": "Shuunyuu ga fuemashita.",
     "example_en": "My income increased.", "example_ru": "Мой доход вырос."},
    {"word": "費用", "level": "N3", "romaji": "hiyou", "en_meaning": "cost / expense", "ru_meaning": "расходы, затраты",
     "example_jp": "費用はいくらですか。", "example_romaji": "Hiyou wa ikura desu ka.",
     "example_en": "How much does it cost?", "example_ru": "Сколько это стоит?"},
    {"word": "値段", "level": "N3", "romaji": "nedan", "en_meaning": "price", "ru_meaning": "цена",
     "example_jp": "値段が高いです。", "example_romaji": "Nedan ga takai desu.",
     "example_en": "The price is high.", "example_ru": "Цена высокая."},
    {"word": "商品", "level": "N3", "romaji": "shouhin", "en_meaning": "goods / merchandise", "ru_meaning": "товар",
     "example_jp": "この商品は人気です。", "example_romaji": "Kono shouhin wa ninki desu.",
     "example_en": "This product is popular.", "example_ru": "Этот товар популярен."},
    {"word": "販売", "level": "N3", "romaji": "hanbai", "en_meaning": "sales / selling", "ru_meaning": "продажа",
     "example_jp": "来月から販売します。", "example_romaji": "Raigetsu kara hanbai shimasu.",
     "example_en": "We'll start selling next month.", "example_ru": "Мы начнём продажи в следующем месяце."},
    {"word": "広告", "level": "N3", "romaji": "koukoku", "en_meaning": "advertisement", "ru_meaning": "реклама",
     "example_jp": "新聞の広告を見ました。", "example_romaji": "Shinbun no koukoku o mimashita.",
     "example_en": "I saw an ad in the newspaper.", "example_ru": "Я видел рекламу в газете."},
    {"word": "契約", "level": "N3", "romaji": "keiyaku", "en_meaning": "contract", "ru_meaning": "договор, контракт",
     "example_jp": "契約にサインしました。", "example_romaji": "Keiyaku ni sain shimashita.",
     "example_en": "I signed the contract.", "example_ru": "Я подписал договор."},
    {"word": "報告", "level": "N3", "romaji": "houkoku", "en_meaning": "report", "ru_meaning": "отчёт, доклад",
     "example_jp": "結果を報告します。", "example_romaji": "Kekka o houkoku shimasu.",
     "example_en": "I'll report the results.", "example_ru": "Я доложу о результатах."},
    {"word": "資料", "level": "N3", "romaji": "shiryou", "en_meaning": "materials / data", "ru_meaning": "материалы, данные",
     "example_jp": "資料を準備します。", "example_romaji": "Shiryou o junbi shimasu.",
     "example_en": "I'll prepare the materials.", "example_ru": "Я подготовлю материалы."},
    {"word": "手段", "level": "N3", "romaji": "shudan", "en_meaning": "means / method", "ru_meaning": "средство, способ",
     "example_jp": "ほかの手段を考えます。", "example_romaji": "Hoka no shudan o kangaemasu.",
     "example_en": "I'll think of another method.", "example_ru": "Я подумаю о другом способе."},
    {"word": "方法", "level": "N3", "romaji": "houhou", "en_meaning": "method / way", "ru_meaning": "метод, способ",
     "example_jp": "いい方法を見つけました。", "example_romaji": "Ii houhou o mitsukemashita.",
     "example_en": "I found a good method.", "example_ru": "Я нашёл хороший способ."},
    {"word": "目的", "level": "N3", "romaji": "mokuteki", "en_meaning": "purpose / goal", "ru_meaning": "цель",
     "example_jp": "旅行の目的は何ですか。", "example_romaji": "Ryokou no mokuteki wa nan desu ka.",
     "example_en": "What is the purpose of your trip?", "example_ru": "Какова цель вашей поездки?"},
    {"word": "目標", "level": "N3", "romaji": "mokuhyou", "en_meaning": "objective / target", "ru_meaning": "цель, ориентир",
     "example_jp": "今年の目標を決めました。", "example_romaji": "Kotoshi no mokuhyou o kimemashita.",
     "example_en": "I set this year's goal.", "example_ru": "Я определил цель на этот год."},
    {"word": "結論", "level": "N3", "romaji": "ketsuron", "en_meaning": "conclusion", "ru_meaning": "вывод, заключение",
     "example_jp": "結論を出しましょう。", "example_romaji": "Ketsuron o dashimashou.",
     "example_en": "Let's reach a conclusion.", "example_ru": "Давайте сделаем вывод."},
    {"word": "意見", "level": "N3", "romaji": "iken", "en_meaning": "opinion", "ru_meaning": "мнение",
     "example_jp": "意見を聞かせてください。", "example_romaji": "Iken o kikasete kudasai.",
     "example_en": "Please let me hear your opinion.", "example_ru": "Скажите, пожалуйста, ваше мнение."},
]


def main():
    conn = sqlite3.connect(DB_NAME)
    cur = conn.cursor()

    cur.execute("SELECT word FROM words")
    existing = {row[0] for row in cur.fetchall()}

    inserted = skipped = 0
    skipped_words = []
    for w in NEW_WORDS:
        if w["word"] in existing:
            skipped += 1
            skipped_words.append(w["word"])
            continue
        cur.execute(
            """INSERT INTO words
               (word, level, romaji, en_meaning, ru_meaning,
                example_jp, example_romaji, example_en, example_ru)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (w["word"], w["level"], w["romaji"], w["en_meaning"], w["ru_meaning"],
             w["example_jp"], w["example_romaji"], w["example_en"], w["example_ru"])
        )
        inserted += 1

    conn.commit()
    cur.execute("SELECT level, COUNT(*) FROM words GROUP BY level ORDER BY level DESC")
    counts = cur.fetchall()
    conn.close()

    print(f"✅ Inserted {inserted}, skipped {skipped} already present.")
    if skipped_words:
        print(f"   Skipped: {', '.join(skipped_words)}")
    print("\nCurrent word counts:")
    for level, n in counts:
        gap = 300 - n
        note = f"  ({gap} to reach 300)" if gap > 0 else "  ✅"
        print(f"   {level}: {n}{note}")
    print("\nNow run:  python3 validate_words.py")


if __name__ == "__main__":
    main()
